application: chengfoliotest
version: 1
runtime: php
api_version: 1

handlers:

  - url: /css
    static_dir: chengfolio/css

  - url: /js
    static_dir: chengfolio/js

  - url: /
    script: chengfolio/view/index.php
