application: chengfoliotest
version: 3
runtime: php
api_version: 1

handlers:

  - url: /css
    static_dir: v3/css

  - url: /js
    static_dir: v3/js

  - url: /img
    static_dir: v3/img

  # - url: /img/(.+)/(.+)
  #   static_files: /img/\1/\2
  #   upload: v3/img/(.+)/(.+)

  - url: /
    script: v3/view/index.php

  - url: /work
    script: v3/view/work.php

  - url: /view/(.+)
    script: v3/view/\1

  - url: /view/component/(.+)
    script: v3/view/component/\1

  - url: /work/heymenu
    script: v3/view/work/heymenu.php

  - url: /work/ivylla
    script: v3/view/work/ivylla.php

  - url: /view/work/(.+)
    script: v3/view/work/\1

  - url: /view/blog/(.+)
    script: v3/view/blog/\1