application: chengfoliotest
version: 1
runtime: php
api_version: 1

handlers:

  - url: /css
    static_dir: chengfolio/css

  - url: /js
    static_dir: chengfolio/js

  - url: /img
    static_dir: chengfolio/img

  # - url: /img/(.+)/(.+)
  #   static_files: /img/\1/\2
  #   upload: chengfolio/img/(.+)/(.+)

  - url: /
    script: chengfolio/view/index.php

  - url: /view/(.+)
    script: chengfolio/view/\1

  - url: /view/component/(.+)
    script: chengfolio/view/component/\1

  - url: /view/work/(.+)
    script: chengfolio/view/work/\1

  - url: /view/blog/(.+)
    script: chengfolio/view/blog/\1