application: aaronchengportfolio
version: 1
runtime: python
api_version: 1

handlers:
  - url: /css
    static_dir: static/css

  - url: /js
    static_dir: static/js

  - url: /img
    static_dir: static/img

  - url: /
    static_files: static/index.html
    upload: static/index.html

  - url: /aerofs.html
    static_files: static/aerofs.html
    upload: static/aerofs.html

  - url: /agilecredit.html
    static_files: static/agilecredit.html
    upload: static/agilecredit.html

  - url: /ambassador.html
    static_files: static/ambassador.html
    upload: static/ambassador.html

  - url: /boutiquesui.html
    static_files: static/boutiquesui.html
    upload: static/boutiquesui.html

  - url: /chengfolio.html
    static_files: static/chengfolio.html
    upload: static/chengfolio.html

  - url: /digitalcloset.html
    static_files: static/digitalcloset.html
    upload: static/digitalcloset.html

  - url: /googlemap.html
    static_files: static/googlemap.html
    upload: static/googlemap.html

  - url: /grabbymouse.html
    static_files: static/grabbymouse.html
    upload: static/grabbymouse.html

  - url: /hummingbird.html
    static_files: static/hummingbird.html
    upload: static/hummingbird.html

  - url: /index.html
    static_files: static/index.html
    upload: static/index.html

  - url: /ivylla.html
    static_files: static/ivylla.html
    upload: static/ivylla.html

  - url: /pin.html
    static_files: static/pin.html
    upload: static/pin.html

  - url: /leap.html
    static_files: static/leap.html
    upload: static/leap.html

  - url: /me.html
    static_files: static/me.html
    upload: static/me.html

  - url: /parkinghousing.html
    static_files: static/parkinghousing.html
    upload: static/parkinghousing.html

  - url: /unisextoilet.html
    static_files: static/unisextoilet.html
    upload: static/unisextoilet.html

  - url: /test/index.php
    script: static/test/index.php

  - url: /test/vendor/autoload.php
    script: static/test/vendor/autoload.php

  - url: /test/lib/pico.php
    script: static/test/lib/pico.php

  - url: /test/themes/(.+)/assets/(.+)
    static_files: /test/themes/\1/assets/\2
    upload: /test/themes/(.+)/assets/(.+)


  # GoogleMapsColorizr
  - url: /GoogleMapsColorizr/css
    static_dir: static/GoogleMapsColorizr/css

  - url: /GoogleMapsColorizr/javascript
    static_dir: static/GoogleMapsColorizr/javascript

  - url: /GoogleMapsColorizr/fonts
    static_dir: static/GoogleMapsColorizr/fonts

  - url: /GoogleMapsColorizr
    static_files: static/GoogleMapsColorizr/index.html
    upload: static/GoogleMapsColorizr/index.html

  - url: /GoogleMapsColorizr/(.*\.html)
    static_files: static/GoogleMapsColorizr/\1
    upload: static/GoogleMapsColorizr/(.*\.html)

  # v2.0
  - url: /v2.0/css
    static_dir: static/v2.0/css

  - url: /v2.0/scripts/1.1
    static_dir: static/v2.0/scripts/1.1

  - url: /v2.0/js
    static_dir: static/v2.0/js

  - url: /v2.0/images
    static_dir: static/v2.0/images

  - url: /v2.0
    static_files: static/v2.0/index.html
    upload: static/v2.0/index.html

  - url: /v2.0/(.*\.html)
    static_files: static/v2.0/\1
    upload: static/v2.0/(.*\.html)

  - url: /.*
    static_files: static/404.html
    upload: static/404.html