application: aaronchengportfolio
version: 1
runtime: php55
api_version: 1

handlers:

  - url: /css
    static_dir: v3/css

  - url: /js
    static_dir: v3/js

  - url: /img
    static_dir: v3/img

  # - url: /img/(.+)/(.+)
  #   static_files: /img/\1/\2
  #   upload: v3/img/(.+)/(.+)

# Site map
  - url: /sitemap.xml
    static_files: v3/view/sitemap.xml
    upload: v3/view/sitemap.xml

  - url: /
    script: v3/view/index.php

  - url: /work
    script: v3/view/work.php

  - url: /about
    script: v3/view/about.php

  - url: /blog
    script: v3/view/blog.php


# Google Map Customizer
  - url: /gmc
    script: v3/view/gmc.php

  - url: /google_map_customizer
    script: v3/view/gmc.php

  - url: /googlemap.html
    script: v3/view/gmc.php

  - url: /GoogleMapsColorizr
    script: v3/view/gmc/GoogleMapsColorizr/index.html

  - url: /GoogleMapsColorizr/css
    static_dir: v3/view/gmc/GoogleMapsColorizr/css

  - url: /GoogleMapsColorizr/javascript
    static_dir: v3/view/gmc/GoogleMapsColorizr/javascript

  - url: /view/(.+)
    script: v3/view/\1

  - url: /view/work/(.+)
    script: v3/view/work/\1

  - url: /view/blog/(.+)
    script: v3/view/blog/\1

  - url: /view/component/(.+)
    script: v3/view/component/\1


# work
  - url: /work/striim_flow_designer
    script: v3/view/work/striim_flow_designer.php

  - url: /work/5th_avenue
    script: v3/view/work/5th_avenue.php

  - url: /work/heymenu
    script: v3/view/work/heymenu.php

  - url: /work/ivylla
    script: v3/view/work/ivylla.php

  - url: /work/boutique_sui
    script: v3/view/work/boutique_sui.php

  - url: /work/pin
    script: v3/view/work/pin.php

  - url: /work/reclink
    script: v3/view/work/reclink.php

  - url: /work/grabby_mouse
    script: v3/view/work/grabby_mouse.php

  - url: /work/parking_housing
    script: v3/view/work/parking_housing.php

# blog
  - url: /blog/how_to_customize_google_map_and_export_high_quality_images_using_google_map_customizer
    script: v3/view/blog/how_to_customize_google_map_and_export_high_quality_images_using_google_map_customizer.php

  - url: /blog/my_new_site_launched
    script: v3/view/blog/my_new_site_launched.php

  - url: /blog/shopping_cart_ui_design
    script: v3/view/blog/shopping_cart_ui_design.php

  - url: /.*
    script: v3/view/404.php